# Generated by Django 6.0 on 2025-12-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='requires_response',
            field=models.BooleanField(default=False, help_text='Does this message require accept/decline?'),
        ),
        migrations.AddField(
            model_name='message',
            name='response_status',
            field=models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('NONE', 'No Response Required')], default='NONE', max_length=10),
        ),
    ]
