# Generated by Django 6.0 on 2025-12-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_message_options_remove_message_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of credits requested', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='credit_status',
            field=models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('NONE', 'No Response Required')], default='NONE', help_text='Status of credit request', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='is_credit_request',
            field=models.BooleanField(default=False, help_text='Is this a credit transfer request?'),
        ),
    ]
